// <auto-generated />
using System;
using EvoluaPonto.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EvoluaPonto.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251229175941_RmvAtivoFeriados")]
    partial class RmvAtivoFeriados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EvoluaPonto.Api.Models.ModelEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.HasKey("Id");

                    b.ToTable("empresas");
                });

            modelBuilder.Entity("EvoluaPonto.Api.Models.ModelEstabelecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logradouro");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<decimal?>("RaioKm")
                        .HasColumnType("numeric")
                        .HasColumnName("raio_km");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("estabelecimentos");
                });

            modelBuilder.Entity("EvoluaPonto.Api.Models.ModelFeriadoPersonalizado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid?>("EstabelecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EstabelecimentoId");

                    b.ToTable("feriados_personalizados");
                });

            modelBuilder.Entity("EvoluaPonto.Api.Models.ModelFuncionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cargo")
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EstabelecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.Property<string>("HorarioContratual")
                        .HasColumnType("text")
                        .HasColumnName("horario_contratual");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId");

                    b.ToTable("funcionarios");
                });

            modelBuilder.Entity("EvoluaPonto.Api.Models.ModelRegistroPonto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AdminIdAnalise")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id_analise");

                    b.Property<string>("ComprovanteUrl")
                        .HasColumnType("text")
                        .HasColumnName("comprovante_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataAnalise")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_analise");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("foto_url");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<string>("GeolocalizacaoIp")
                        .HasColumnType("text")
                        .HasColumnName("geolocalizacao_ip");

                    b.Property<string>("HashSha256")
                        .HasColumnType("text")
                        .HasColumnName("hash_sha256");

                    b.Property<string>("JustificativaAdmin")
                        .HasColumnType("text")
                        .HasColumnName("justificativa_admin");

                    b.Property<string>("JustificativaFuncionario")
                        .HasColumnType("text")
                        .HasColumnName("justificativa_funcionario");

                    b.Property<long?>("Nsr")
                        .HasColumnType("bigint")
                        .HasColumnName("nsr");

                    b.Property<bool>("RegistroManual")
                        .HasColumnType("boolean")
                        .HasColumnName("registro_manual");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status_solicitacao");

                    b.Property<DateTime>("TimestampMarcacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_marcacao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("registros_ponto");
                });

            modelBuilder.Entity("EvoluaPonto.Api.Models.ModelUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AcessoPermitido")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EvoluaPonto.Api.Models.ModelEstabelecimento", b =>
                {
                    b.HasOne("EvoluaPonto.Api.Models.ModelEmpresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("EvoluaPonto.Api.Models.ModelFeriadoPersonalizado", b =>
                {
                    b.HasOne("EvoluaPonto.Api.Models.ModelEmpresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("EvoluaPonto.Api.Models.ModelEstabelecimento", "Estabelecimento")
                        .WithMany()
                        .HasForeignKey("EstabelecimentoId");

                    b.Navigation("Empresa");

                    b.Navigation("Estabelecimento");
                });

            modelBuilder.Entity("EvoluaPonto.Api.Models.ModelFuncionario", b =>
                {
                    b.HasOne("EvoluaPonto.Api.Models.ModelEstabelecimento", "Estabelecimento")
                        .WithMany()
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estabelecimento");
                });

            modelBuilder.Entity("EvoluaPonto.Api.Models.ModelRegistroPonto", b =>
                {
                    b.HasOne("EvoluaPonto.Api.Models.ModelFuncionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("EvoluaPonto.Api.Models.ModelUsuario", b =>
                {
                    b.HasOne("EvoluaPonto.Api.Models.ModelFuncionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
