server {
    listen 80;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html;

    # Essa parte garante que o HTML principal nunca fique velho
    location /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    include /etc/nginx/mime.types;

    # Assets podem ter cache, pois mudam de nome (hash) quando atualizam
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public";
    }
}