server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Gzip para velocidade
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript font/woff2;

    # Roteamento do React (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache de arquivos estáticos e ícones (Isso conserta seus bugs de ícones!)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|pdf)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}