
services:
  database:
    image: postgres:15-alpine
    container_name: database_service
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: gabriellange/evolua-ponto-backend:latest 
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_service
    restart: always
    environment:
      # Passando a string de conexão para a API .NET
      ConnectionStrings__DefaultConnection: "Host=database;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};"
      Jwt__Secret: ${JWT_SECRET}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__Issuer: ${JWT_ISSUER}
      Supabase__Url: ${SUPABASE_URL} 
      Supabase__ServiceRoleKey: ${SUPABASE_KEY}
    depends_on:
      - database

  frontend:
    image: gabriellange/evolua-ponto-frontend:latest 
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: frontend_service
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5555:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - database

volumes:
  postgres_data:
  pgadmin_data: